name: Update GitHub Activity

on:
  schedule:
    - cron: "37 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: HouMinXi
          MAX_LINES: 15
          COMMIT_MSG: "chore: update activity"
