name: Update PR Stats

on:
  schedule:
    - cron: "23 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PRs card
        uses: Daraan/pr-stats-action@main
        with:
          card: prs
          username: ${{ github.repository_owner }}
          theme: transparent
          path: profile/prs-
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "chore: update PR contribution cards" || exit 0
          git push
